name: Cppcheck

on:
  push:
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: cppcheck --version && cppcheck --suppress=*:*/src/third_party/* --enable=all . --error-exitcode=1
